"""bio,profile,user_id Migration

Revision ID: 7676dca9af0f
Revises: b498b9eefdfb
Create Date: 2022-05-15 17:35:18.616452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7676dca9af0f'
down_revision = 'b498b9eefdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'profile')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
