"""update Migration

Revision ID: 76dafd8bb7f0
Revises: 91b71e6aad72
Create Date: 2022-05-18 02:38:32.361548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dafd8bb7f0'
down_revision = '91b71e6aad72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deletes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name='deletes_blog_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deletes_pkey')
    )
    # ### end Alembic commands ###
